default: &default
  pool: 5
  timeout: 5000

development:
  <<: *default 
  adapter: <%= ENV['DB_ADAPTER']  %>
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

test:
  <<: *default
  adapter: <%= ENV['DB_ADAPTER']  %>
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DB_NAME_TEST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

