default: &default
  pool: 5
  timeout: 5000

development:
  <<: *default
  adapter: postgresql 
  host: localhost
  database: fakebookdb
  username: fakebook
  password: 1234
  
  adapter: <%= ENV['DB_ADAPTER']  %>
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

test:
  <<: *default
  adapter: sqlite3
  database: db/test.sqlite3

